apiVersion: apps/v1
kind: Deployment
metadata:
  name: green-backend
  labels:
    app: backend
    version: green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
      version: green
  template:
    metadata:
      labels:
        app: backend
        version: green
    spec:
      containers:
      - name: backend
        image: <ECR_REPOSITORY_URL>:latest
        ports:
        - containerPort: 5000
