apiVersion: apps/v1
kind: Deployment
metadata:
  name: green-backend
  labels:
    app: backend
    version: green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
      version: green
  template:
    metadata:
      labels:
        app: backend
        version: green
    spec:
      containers:
      - name: backend
        image: 180294186777.dkr.ecr.ap-south-1.amazonaws.com/my-repo:latest
        ports:
        - containerPort: 5000
