apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: basic-cluster           # Name of the EKS cluster
  region: ap-south-1            # AWS region for the cluster

nodeGroups:
  - name: ng-1
    instanceType: t2.medium     # Changed instance type to t2.medium
    desiredCapacity: 1          # Set desired capacity to 2 nodes
    volumeSize: 8               # EBS volume size per node, set to 8GB
    ssh:
      publicKeyPath: ~/.ssh/id_ed25519.pub  # Specify your SSH key file explicitly
