apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: kube-system
  labels:
    k8s-app: fluentd-cloudwatch
data:
  fluent.conf: |
    @include containers.conf
  
  containers.conf: |
    <source>
      @type tail
      path /var/log/containers/*.log
      pos_file /var/log/fluentd-containers.log.pos
      tag kubernetes.*
      format json
    </source>

    <filter kubernetes.**>
       @type kubernetes_metadata
    </filter>

    <match kubernetes.**>
      @type forward
      @log_level info
      <server>
        host fluentd-service  # Replace with your service name for the Otel Collector
        port 8006
      </server>
    </match>
