apiVersion: v1
kind: Service
metadata:
  name: fluentd-service
  namespace: kube-system
  labels:
    app: fluentd-cloudwatch
spec:
  selector:
    k8s-app: fluentd-cloudwatch  # Matches the labels in the DaemonSet pods
  ports:
    - protocol: TCP
      port: 8006  # Port exposed by the service
      targetPort: 8006  # Port on which Fluentd is listening
  type: ClusterIP



---

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd-cloudwatch
  namespace: kube-system
  labels:
    k8s-app: fluentd-cloudwatch
spec:
  selector:
    matchLabels:
      k8s-app: fluentd-cloudwatch
  template:
    metadata:
      labels:
        k8s-app: fluentd-cloudwatch
      annotations:
        iam.amazonaws.com/role:  arn:aws:iam::180294186777:role/eksctl-demo-cluster-addon-iamserviceaccount-k-Role1-i5kMF2epe38r
    spec:
      serviceAccountName: fluentd  # Ensure this matches the created service account
      containers:
        - name: fluentd-cloudwatch
          image: fluent/fluentd-kubernetes-daemonset:v1.16.5-debian-cloudwatch-1.0
          imagePullPolicy: IfNotPresent
          env:
            - name: AWS_REGION
              value: us-east-1
            - name: AWS_EKS_CLUSTER_NAME
              value: demo-cluster
            - name: FLUENT_ELASTICSEARCH_HOST
              value: "fluentd-service"
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              memory: 512Mi
          volumeMounts:
            - name: config-volume
              mountPath: /config-volume
            - name: fluentdconf
              mountPath: /fluentd/etc
            - name: varlog
              mountPath: /var/log
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
            - name: runlogjournal
              mountPath: /run/log/journal
              readOnly: true
      initContainers:
        - name: copy-fluentd-config
          image: busybox
          imagePullPolicy: Always
          command: ["sh", "-c", "cp /config-volume/* /fluentd/etc"]
          volumeMounts:
            - name: config-volume
              mountPath: /config-volume
            - name: fluentdconf
              mountPath: /fluentd/etc
      volumes:
        - name: config-volume
          configMap:
            name: fluentd-config
        - name: fluentdconf
          emptyDir: {}
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
        - name: runlogjournal
          hostPath:
            path: /run/log/journal
